//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eltizam.Resource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jupiter.Resource.Resources.Master", typeof(Master).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type Name.
        /// </summary>
        public static string ActivityTypeName {
            get {
                return ResourceManager.GetString("ActivityTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Year.
        /// </summary>
        public static string AddYear {
            get {
                return ResourceManager.GetString("AddYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMT.
        /// </summary>
        public static string AMT {
            get {
                return ResourceManager.GetString("AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMV.
        /// </summary>
        public static string AMV {
            get {
                return ResourceManager.GetString("AMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical Departments.
        /// </summary>
        public static string AnalyticalDepartments {
            get {
                return ResourceManager.GetString("AnalyticalDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical GL Name.
        /// </summary>
        public static string AnalyticalName {
            get {
                return ResourceManager.GetString("AnalyticalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Charter Details.
        /// </summary>
        public static string APICharterDetails {
            get {
                return ResourceManager.GetString("APICharterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Charter Details Form.
        /// </summary>
        public static string APICharterDetailsForm {
            get {
                return ResourceManager.GetString("APICharterDetailsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  API Charter Summary Details.
        /// </summary>
        public static string APICharterSummaryDetails {
            get {
                return ResourceManager.GetString("APICharterSummaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Group Leader.
        /// </summary>
        public static string APIGroupLeader {
            get {
                return ResourceManager.GetString("APIGroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API IPD.
        /// </summary>
        public static string APIIPD {
            get {
                return ResourceManager.GetString("APIIPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API IPD Details.
        /// </summary>
        public static string APIIPDDetails {
            get {
                return ResourceManager.GetString("APIIPDDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API IPD Details Form.
        /// </summary>
        public static string APIIPDDetailsForm {
            get {
                return ResourceManager.GetString("APIIPDDetailsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API IPD List.
        /// </summary>
        public static string APIIPDList {
            get {
                return ResourceManager.GetString("APIIPDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Market Price.
        /// </summary>
        public static string APIMarketPrice {
            get {
                return ResourceManager.GetString("APIMarketPrice", resourceCulture);
            }
        }
        
       
        public static string APIReq {
            get {
                return ResourceManager.GetString("APIReq", resourceCulture);
            }
        }
        
       
        public static string APiReq_EltizamKg_
		{
            get {
                return ResourceManager.GetString("APiReq(EltizamKg)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API RnD.
        /// </summary>
        public static string APIRnd {
            get {
                return ResourceManager.GetString("APIRnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API RnD Details.
        /// </summary>
        public static string APIRndDetails {
            get {
                return ResourceManager.GetString("APIRndDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Rnd Details Form.
        /// </summary>
        public static string APIRndDetailsForm {
            get {
                return ResourceManager.GetString("APIRndDetailsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APISourcing Name.
        /// </summary>
        public static string APISourcingName {
            get {
                return ResourceManager.GetString("APISourcingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Target RMC+CCPC.
        /// </summary>
        public static string APITargetRMC_CCPC {
            get {
                return ResourceManager.GetString("APITargetRMC_CCPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Generics.
        /// </summary>
        public static string ApprovedGenerics {
            get {
                return ResourceManager.GetString("ApprovedGenerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Genetics.
        /// </summary>
        public static string ApprovedGenetics {
            get {
                return ResourceManager.GetString("ApprovedGenetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARD.
        /// </summary>
        public static string ARD {
            get {
                return ResourceManager.GetString("ARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Logs.
        /// </summary>
        public static string AuditLogs {
            get {
                return ResourceManager.GetString("AuditLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Size Number Name.
        /// </summary>
        public static string BatchSizeNumberName {
            get {
                return ResourceManager.GetString("BatchSizeNumberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE Requirement Name.
        /// </summary>
        public static string BERequirementName {
            get {
                return ResourceManager.GetString("BERequirementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Approval.
        /// </summary>
        public static string BudgetApproval {
            get {
                return ResourceManager.GetString("BudgetApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit Name.
        /// </summary>
        public static string BusinessUnitName {
            get {
                return ResourceManager.GetString("BusinessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Inactive Role, User assigned to this Role..
        /// </summary>
        public static string CanNotInactiveRole {
            get {
                return ResourceManager.GetString("CanNotInactiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Other Expenditure.
        /// </summary>
        public static string CapitalOtherExpenditure {
            get {
                return ResourceManager.GetString("CapitalOtherExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profile.
        /// </summary>
        public static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments1 {
            get {
                return ResourceManager.GetString("Comments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Patent Specific.
        /// </summary>
        public static string CommentsPatentSpecific {
            get {
                return ResourceManager.GetString("CommentsPatentSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Batch Size (Qtr).
        /// </summary>
        public static string CommercialBatchSize {
            get {
                return ResourceManager.GetString("CommercialBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Batch Size (Qtr).
        /// </summary>
        public static string CommercialBatchSize_Qtr_ {
            get {
                return ResourceManager.GetString("CommercialBatchSize(Qtr)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Details.
        /// </summary>
        public static string CommercialDetails {
            get {
                return ResourceManager.GetString("CommercialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Of Litigation.
        /// </summary>
        public static string CostOfLitication {
            get {
                return ResourceManager.GetString("CostOfLitication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Region.
        /// </summary>
        public static string CountryRegion {
            get {
                return ResourceManager.GetString("CountryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Countrys {
            get {
                return ResourceManager.GetString("Countrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countrys.
        /// </summary>
        public static string Countrys1 {
            get {
                return ResourceManager.GetString("Countrys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exclusivity.
        /// </summary>
        public static string DataExclusivity {
            get {
                return ResourceManager.GetString("DataExclusivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA Name.
        /// </summary>
        public static string DIAName {
            get {
                return ResourceManager.GetString("DIAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage Form Name.
        /// </summary>
        public static string DosageFormName {
            get {
                return ResourceManager.GetString("DosageFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage Type.
        /// </summary>
        public static string DosageForms {
            get {
                return ResourceManager.GetString("DosageForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage Name.
        /// </summary>
        public static string DosageName {
            get {
                return ResourceManager.GetString("DosageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs Category.
        /// </summary>
        public static string DrugsCategory {
            get {
                return ResourceManager.GetString("DrugsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibit.
        /// </summary>
        public static string Exhibit {
            get {
                return ResourceManager.GetString("Exhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exipient Name.
        /// </summary>
        public static string ExipientName {
            get {
                return ResourceManager.GetString("ExipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Region Name.
        /// </summary>
        public static string ExpenseRegionName {
            get {
                return ResourceManager.GetString("ExpenseRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Application Name.
        /// </summary>
        public static string ExtensionApplicationName {
            get {
                return ResourceManager.GetString("ExtensionApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Expiry Date.
        /// </summary>
        public static string ExtensionExpiryDate {
            get {
                return ResourceManager.GetString("ExtensionExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing Type Name.
        /// </summary>
        public static string FilingTypeName {
            get {
                return ResourceManager.GetString("FilingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling Type.
        /// </summary>
        public static string FillingType {
            get {
                return ResourceManager.GetString("FillingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Selection.
        /// </summary>
        public static string FinalSelection {
            get {
                return ResourceManager.GetString("FinalSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDF Finance.
        /// </summary>
        public static string FinancePIDF {
            get {
                return ResourceManager.GetString("FinancePIDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Rates.
        /// </summary>
        public static string FinanceRates {
            get {
                return ResourceManager.GetString("FinanceRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form RND Division Name.
        /// </summary>
        public static string FormRNDDivisionName {
            get {
                return ResourceManager.GetString("FormRNDDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation.
        /// </summary>
        public static string Formulation {
            get {
                return ResourceManager.GetString("Formulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Formulation Details.
        /// </summary>
        public static string FormulationDetails {
            get {
                return ResourceManager.GetString("FormulationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation Name.
        /// </summary>
        public static string FormulationName {
            get {
                return ResourceManager.GetString("FormulationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation Quantity.
        /// </summary>
        public static string FormulationQuantity {
            get {
                return ResourceManager.GetString("FormulationQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation Quantity Required KG/Gm Stage.
        /// </summary>
        public static string FormulationQuantityRequiredKG_GmStage {
            get {
                return ResourceManager.GetString("FormulationQuantityRequiredKG/GmStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Of Cost.
        /// </summary>
        public static string FreeOfCost {
            get {
                return ResourceManager.GetString("FreeOfCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headwise Budget (In Lacs).
        /// </summary>
        public static string HeadwiseBudget_InLacs_ {
            get {
                return ResourceManager.GetString("HeadwiseBudget(InLacs)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impurity.
        /// </summary>
        public static string Impurity {
            get {
                return ResourceManager.GetString("Impurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In House.
        /// </summary>
        public static string InHouses {
            get {
                return ResourceManager.GetString("InHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Licenses.
        /// </summary>
        public static string InLicenses {
            get {
                return ResourceManager.GetString("InLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovators.
        /// </summary>
        public static string Innovators {
            get {
                return ResourceManager.GetString("Innovators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPD Management.
        /// </summary>
        public static string IPDManagement {
            get {
                return ResourceManager.GetString("IPDManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Evaluation.
        /// </summary>
        public static string IPEvalution {
            get {
                return ResourceManager.GetString("IPEvalution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISD country Code.
        /// </summary>
        public static string IsdcountryCode {
            get {
                return ResourceManager.GetString("IsdcountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched Generics.
        /// </summary>
        public static string LaunchedGenerics {
            get {
                return ResourceManager.GetString("LaunchedGenerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched Genetics.
        /// </summary>
        public static string LaunchedGenetics {
            get {
                return ResourceManager.GetString("LaunchedGenetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Status.
        /// </summary>
        public static string LegalStatus {
            get {
                return ResourceManager.GetString("LegalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manhour Estimates.
        /// </summary>
        public static string ManhourEstimates {
            get {
                return ResourceManager.GetString("ManhourEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManHour Rates.
        /// </summary>
        public static string ManHourRates {
            get {
                return ResourceManager.GetString("ManHourRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Name.
        /// </summary>
        public static string ManufacturingName {
            get {
                return ResourceManager.GetString("ManufacturingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Details (New Port / CGI Details).
        /// </summary>
        public static string MarketDetailsNewPortCGIDetails {
            get {
                return ResourceManager.GetString("MarketDetailsNewPortCGIDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Extension / New Product.
        /// </summary>
        public static string MarketExtensions {
            get {
                return ResourceManager.GetString("MarketExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Extenstion Name.
        /// </summary>
        public static string MarketExtenstionName {
            get {
                return ResourceManager.GetString("MarketExtenstionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Growth %.
        /// </summary>
        public static string MarketGrowth {
            get {
                return ResourceManager.GetString("MarketGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market ID.
        /// </summary>
        public static string MarketID {
            get {
                return ResourceManager.GetString("MarketID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Name.
        /// </summary>
        public static string MarketName {
            get {
                return ResourceManager.GetString("MarketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Size.
        /// </summary>
        public static string MarketSize {
            get {
                return ResourceManager.GetString("MarketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Size In Unit.
        /// </summary>
        public static string MarketSizeInUnit {
            get {
                return ResourceManager.GetString("MarketSizeInUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Size in Units as Launch.
        /// </summary>
        public static string MarketSizeinUnitsasLaunch {
            get {
                return ResourceManager.GetString("MarketSizeinUnitsasLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecule Name.
        /// </summary>
        public static string MoleculeName {
            get {
                return ResourceManager.GetString("MoleculeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Employee.
        /// </summary>
        public static string NoOfEmployee {
            get {
                return ResourceManager.GetString("NoOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Oldpassword {
            get {
                return ResourceManager.GetString("Oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage Form.
        /// </summary>
        public static string OralName {
            get {
                return ResourceManager.GetString("OralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Expiry Date.
        /// </summary>
        public static string OriginalExpiraDate {
            get {
                return ResourceManager.GetString("OriginalExpiraDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Type Name.
        /// </summary>
        public static string PackagingTypeName {
            get {
                return ResourceManager.GetString("PackagingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Packaging Type.
        /// </summary>
        public static string PackagingTypes {
            get {
                return ResourceManager.GetString("PackagingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Type Name.
        /// </summary>
        public static string PackingTypeName {
            get {
                return ResourceManager.GetString("PackingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Size Name.
        /// </summary>
        public static string PackSizeName {
            get {
                return ResourceManager.GetString("PackSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Size.
        /// </summary>
        public static string PackStyle {
            get {
                return ResourceManager.GetString("PackStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent Details.
        /// </summary>
        public static string PatentDetails {
            get {
                return ResourceManager.GetString("PatentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent Number.
        /// </summary>
        public static string PatentNumber {
            get {
                return ResourceManager.GetString("PatentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent Number.
        /// </summary>
        public static string PatentNumber1 {
            get {
                return ResourceManager.GetString("PatentNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent Status.
        /// </summary>
        public static string PatentStatus {
            get {
                return ResourceManager.GetString("PatentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBF &amp; API.
        /// </summary>
        public static string PBFAPI {
            get {
                return ResourceManager.GetString("PBFAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBFAPI List.
        /// </summary>
        public static string PBFAPIList {
            get {
                return ResourceManager.GetString("PBFAPIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDF Commercial.
        /// </summary>
        public static string PIDFCommercial {
            get {
                return ResourceManager.GetString("PIDFCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDF Commercial Details.
        /// </summary>
        public static string PIDFCommercialDetails {
            get {
                return ResourceManager.GetString("PIDFCommercialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDF Commercial List.
        /// </summary>
        public static string PIDFCommercialList {
            get {
                return ResourceManager.GetString("PIDFCommercialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDF Management.
        /// </summary>
        public static string PIDFManagement {
            get {
                return ResourceManager.GetString("PIDFManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Players / ANDA.
        /// </summary>
        public static string PIDFNO {
            get {
                return ResourceManager.GetString("PIDFNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Name .
        /// </summary>
        public static string PlantNameName {
            get {
                return ResourceManager.GetString("PlantNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant QC.
        /// </summary>
        public static string PlantQC {
            get {
                return ResourceManager.GetString("PlantQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRD Departments.
        /// </summary>
        public static string PRDDepartments {
            get {
                return ResourceManager.GetString("PRDDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Discounting %.
        /// </summary>
        public static string PriceDiscounting {
            get {
                return ResourceManager.GetString("PriceDiscounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Erosion %.
        /// </summary>
        public static string PriceErosion {
            get {
                return ResourceManager.GetString("PriceErosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Packaging.
        /// </summary>
        public static string ProductPackaging {
            get {
                return ResourceManager.GetString("ProductPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Packaging Type.
        /// </summary>
        public static string ProductPackagingType {
            get {
                return ResourceManager.GetString("ProductPackagingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Strength.
        /// </summary>
        public static string ProductStrength {
            get {
                return ResourceManager.GetString("ProductStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductStrengthName.
        /// </summary>
        public static string ProductStrengthName {
            get {
                return ResourceManager.GetString("ProductStrengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Name.
        /// </summary>
        public static string ProductTypeName {
            get {
                return ResourceManager.GetString("ProductTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Complexity.
        /// </summary>
        public static string ProjectComplexity {
            get {
                return ResourceManager.GetString("ProjectComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project End Date.
        /// </summary>
        public static string ProjectEndDate {
            get {
                return ResourceManager.GetString("ProjectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Initiation Date.
        /// </summary>
        public static string ProjectInitiationDate {
            get {
                return ResourceManager.GetString("ProjectInitiationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Cost.
        /// </summary>
        public static string RawMaterialCost {
            get {
                return ResourceManager.GetString("RawMaterialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string RFDApplicant {
            get {
                return ResourceManager.GetString("RFDApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string RFDBrand {
            get {
                return ResourceManager.GetString("RFDBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Batch Size (Qtr).
        /// </summary>
        public static string RFDCommercialBatchSize {
            get {
                return ResourceManager.GetString("RFDCommercialBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indication.
        /// </summary>
        public static string RFDIndication {
            get {
                return ResourceManager.GetString("RFDIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Revenue Potential.
        /// </summary>
        public static string RFDInitialRevenuePotential {
            get {
                return ResourceManager.GetString("RFDInitialRevenuePotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovators.
        /// </summary>
        public static string RFDInnovators {
            get {
                return ResourceManager.GetString("RFDInnovators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Discounting %.
        /// </summary>
        public static string RFDPriceDiscounting {
            get {
                return ResourceManager.GetString("RFDPriceDiscounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Manage.
        /// </summary>
        public static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rupee(In Lacs).
        /// </summary>
        public static string Rupee_InLacs_ {
            get {
                return ResourceManager.GetString("Rupee(InLacs)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Up.
        /// </summary>
        public static string ScaleUp {
            get {
                return ResourceManager.GetString("ScaleUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Life.
        /// </summary>
        public static string ShelfLife {
            get {
                return ResourceManager.GetString("ShelfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Business Partner.
        /// </summary>
        public static string SponsorBusinessPartner {
            get {
                return ResourceManager.GetString("SponsorBusinessPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        public static string Stability {
            get {
                return ResourceManager.GetString("Stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU (IMS Volume).
        /// </summary>
        public static string SU_IMS {
            get {
                return ResourceManager.GetString("SU_IMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU (IMS Volume).
        /// </summary>
        public static string SU_IMSVolume_ {
            get {
                return ResourceManager.GetString("SU(IMSVolume)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Type Code.
        /// </summary>
        public static string TestTypeCode {
            get {
                return ResourceManager.GetString("TestTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Type Name.
        /// </summary>
        public static string TestTypeName {
            get {
                return ResourceManager.GetString("TestTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestT ype Price.
        /// </summary>
        public static string TestTypePrice {
            get {
                return ResourceManager.GetString("TestTypePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline In Months.
        /// </summary>
        public static string TimelineInMonths {
            get {
                return ResourceManager.GetString("TimelineInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total API Req (IMS KG).
        /// </summary>
        public static string TotalAPIReq {
            get {
                return ResourceManager.GetString("TotalAPIReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total API Req (IMS KG).
        /// </summary>
        public static string TotalAPIReq_IMSKg_ {
            get {
                return ResourceManager.GetString("TotalAPIReq(IMSKg)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform  Name.
        /// </summary>
        public static string TransformName {
            get {
                return ResourceManager.GetString("TransformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measurement Name.
        /// </summary>
        public static string UnitofMeasurementName {
            get {
                return ResourceManager.GetString("UnitofMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measurements.
        /// </summary>
        public static string UnitofMeasurements {
            get {
                return ResourceManager.GetString("UnitofMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Role.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manage.
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserMangegment {
            get {
                return ResourceManager.GetString("UserMangegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Name.
        /// </summary>
        public static string WorkflowName {
            get {
                return ResourceManager.GetString("WorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Details.
        /// </summary>
        public static string YearDetails {
            get {
                return ResourceManager.GetString("YearDetails", resourceCulture);
            }
        }
    }
}
